name: Deploy to VPS

on:
  push:
    branches:
      - v2
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production-ionos
    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        # with:
        #   version: 10

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Create .env.production file from GitHub Secrets
        env:
          STRIPE_PK: ${{ secrets.STRIPE_PK }}
          STRIPE_SK: ${{ secrets.STRIPE_SK }}
          STRIPE_WBH_SECRET: ${{ secrets.STRIPE_WBH_SECRET }}
          BASE_URL: ${{ vars.BASE_URL }}
          MONGO_CONN_STR: ${{ secrets.MONGO_CONN_STR }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ADMIN_BOOKING_ID: ${{ secrets.ADMIN_BOOKING_ID }}
          NEARLY_CLOSING_HRS: ${{ secrets.NEARLY_CLOSING_HRS }}
          HAS_CLOSED_HRS: ${{ secrets.HAS_CLOSED_HRS }}
        run: |
          echo "STRIPE_PK=$STRIPE_PK" >> .env.production
          echo "STRIPE_SK=$STRIPE_SK" >> .env.production
          echo "STRIPE_WBH_SECRET=$STRIPE_WBH_SECRET" >> .env.production
          echo "BASE_URL=$BASE_URL" >> .env.production
          echo "MONGO_CONN_STR=$MONGO_CONN_STR" >> .env.production
          echo "EMAIL_HOST=$EMAIL_HOST" >> .env.production
          echo "EMAIL_PORT=$EMAIL_PORT" >> .env.production
          echo "EMAIL_USER=$EMAIL_USER" >> .env.production
          echo "EMAIL_PASS=$EMAIL_PASS" >> .env.production
          echo "JWT_SECRET=$JWT_SECRET" >> .env.production
          echo "ADMIN_BOOKING_ID=$ADMIN_BOOKING_ID" >> .env.production
          echo "NEARLY_CLOSING_HRS=$NEARLY_CLOSING_HRS" >> .env.production
          echo "HAS_CLOSED_HRS=$HAS_CLOSED_HRS" >> .env.production

      - name: Build
        run: NODE_ENV=production pnpm build

      - name: Prune Monorepo for Backend Production
        run: pnpm --filter backend deploy pruned-backend --prod --legacy

      - name: Prepare Backend Bundle
        run: cp .env.production pruned-backend/

      - name: Transfer Backend Bundle to VPS
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          target: /web/inscription-evenements/backend/
          source: "pruned-backend/*"
          overwrite: true
          strip_components: 1

      - name: Transfer Frontend Dist to VPS
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          target: /web/inscription-evenements/frontend/
          source: "frontend/dist/*"
          overwrite: true
          strip_components: 2

      - name: Transfer Nginx Config to VPS
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          target: /etc/nginx/sites-available/
          source: nginx.conf
          overwrite: true

      - name: Reload Backend on VPS
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /web/inscription-evenements/backend
            cp .env.production .env

            if pm2 describe inscription-backend > /dev/null 2>&1; then
              NODE_ENV=production pm2 restart inscription-backend --update-env
            else
              NODE_ENV=production pm2 start dist/main.js --name inscription-backend
            fi
            pm2 save

      - name: Set Frontend Permissions on VPS
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            sudo chown -R www-data:www-data /web/inscription-evenements/frontend
            sudo chmod -R 755 /web/inscription-evenements/frontend

      - name: Reload Nginx on VPS
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            mv /etc/nginx/sites-available/nginx.conf /etc/nginx/sites-available/inscription-evenements.conf
            ln -sf /etc/nginx/sites-available/inscription-evenements.conf /etc/nginx/sites-enabled/inscription-evenements.conf
            sudo nginx -t && sudo nginx -s reload